[package]
name = "reproduction"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk = { version = "0.9.3", package = "gtk4", features = ["v4_16"] }
adw = { version = "0.7.1", package = "libadwaita", features = ["v1_6"] }
